#!/bin/bash
#
# ######################
#                  Variables
# ######################
# varivales are used to not keep writing commands paths or datas in every different situation from the beiginning #
# so we assignle varibale to the changing parts for the script/command exmaple LOG-File-Name , Log-Diretory-path
# and if add $ before log file name and log directory path and ask user imput the value system will generate the data by using the value/user entered log file name or directory path
# let see 
#
#
#

###################
######    Declaring Variables  ###################### 
LOG_FILE_PATH="/c/Users/Me/AWS-CLI-Automation/Logs/" ### this LOG_FILE_PATH is VArriabel
LOG_FILE_NAME=("application.log" "system.log")   #### this LOG_FILE_NAME is array varribale
#########	
#     Array Variable - that can have multiple optional choice 

ERROR_PATTERN_NAME=("ERROR" "FATAL" "CRITICAL") # ***TO access from this variable systyem assigns index like "ERROR"=0 "FATAL"=1 AND so on

LOG_ANALYSIS_REPORT="/c/Users/Me/AWS-CLI-Automation/Logs/Log_Analysis_Report.txt" ### where the analysis report should be saved , there would be cho command at the end that would announce where the report will be storred/saved  

# run find "$LOG_FILE_PATH" -name "*.log" -mtime -1   #### we will be providing absolute path for the script to work from anywhere after example /c/Users/Me/AWS-CLI-Automation/Logs

## we make the value returned/generated by the above command to a variable named LOG_FILE_NAME by doing the following it is called 

      ##  COMMAND SUBSTITUTION *****************###########

LOG_FILE_NAME=$(find "$LOG_FILE_PATH" -name "*.log" -mtime -1) >> $LOG_ANALYSIS_REPORT
echo "analysing log files" > $LOG_ANALYSIS_REPORT
echo "=================================" >> $LOG_ANALYSIS_REPORT

echo -e "\n finding List of log files in updated in last 24 hours" >> $LOG_ANALYSIS_REPORT


echo "which log file you want to analyse" >> $LOG_ANALYSIS_REPORT


echo "Here are the Log files" "$LOG_FILE_NAME" >> $LOG_ANALYSIS_REPORT


#echo "which log file you want to analyse" , not required coz for loop used beloow

#read -p "enter log file name" LOG_FILE_NAME - not required when we use for - do loop  

for LOG_FILE in $LOG_FILE_NAME; do	## LOG_FILE is temprary variable


	for ERROR_PATTERN in ${ERROR_PATTERN_NAME[@]}; do  ### ERROR_PATTERN is temporary variable [@] this ensure each variable in the ERROR_PATTER_NAME is treated individually as compard to LOG_FILE_NAME where the variables are in list 

echo " searching $ERROR_PATTERN in $LOG_FILE " >> $LOG_ANALYSIS_REPORT



grep "$ERROR_PATTERN" "$LOG_FILE" >> $LOG_ANALYSIS_REPORT #to find ERROR files abosulte pathe $LOG_FILE_PATH is not required as this variable is fixed , we could have used for loop for log_file_path as well if there were different paths 

echo -e "\n searching number of $ERROR_PATTERN in $LOG_FILE" >> $LOG_ANALYSIS_REPORT

echo "showing number of $ERROR_PATTERN in $LOG_FILE" >> $LOG_ANALYSIS_REPORT

NUMBER_OF_PROBLEM=$(grep -c "$ERROR_PATTERN" "$LOG_FILE") >> $LOG_ANALYSIS_REPORT # finding number of ERROR files     #### -c after grep is for count off error/fatal/critical log #####


if [ "$NUMBER_OF_PROBLEM" -gt 10 ]; then 
	echo " **warning $ERROR_PATTERN problem count 10 or more in $LOG_FILE ** " >> $LOG_ANALYSIS_REPORT 
fi

done
done

echo "all analysis report are being storored in $LOG_ANALYSIS_REPORT"

